### ISSUE TITLE
Suggestion: {custom_name} in custom-text

### ISSUE THREAD

**Issue by Khrystyian** [DavideBlade/HealthBar-Reloaded#19]
Could you please add support for {custom_name} in the custom-text? That way it displays the custom name of the mob and just adds the health display to it at the end. Thank you!

**Comment by DavideBlade** [comment]
If I have not misunderstood, this is exactly what `{name}` does. With the following configuration, you get the result below.

config.yml:
```yaml
mob-bars:
  enable: true
  text-mode: true
  custom-text-enable: true
  custom-text: '{name} - &a{health}/{max}'
```

locale.yml:
```yaml
CREEPER: CustomName:)
```

Result:
![Creeper with custom name](https://i.imgur.com/4cs8hj1.png)
