### ISSUE TITLE
fast question

### ISSUE THREAD

**Issue by TymekSL** [DavideBlade/HealthBar-Reloaded#21]
I want have bossbar https://prnt.sc/A3kCP4MkV_Ig , which settings i need to turn on to make it? I still see 100% hp on mobs

**Comment by DavideBlade** [comment]
On the [wiki](https://github.com/DavideBlade/HealthBar-Reloaded/wiki/Customization) you have plenty of examples of what you can achieve and how. For the mob bar in the screenshot, you need to use:
```YAML
mob-bars:
  enable: true
  display-style: 1
  text-mode: false
```

Let me know if it works :)
