### ISSUE TITLE
healthbar not working for all mobs 

### ISSUE THREAD

**Issue by SirAltF4** [DavideBlade/HealthBar-Reloaded#22]
my healthbars arent working on zombies, skeletons, creepers and other mobs but the healthbar is working for spiders and most passive mobs so I'm a bit confused on what the issues is

**Comment by DavideBlade** [comment]
Please check the `config.yml`:
```yaml
mob-bars:
  # These mobs won't show the health.
  # The names are the same in locale.yml.
  # To enable all mobs, use: disabled-types: ''
  disabled-types: creeper,zombie,skeleton,iron_golem
```
