### ISSUE TITLE
Health not showing on mobs unless 'always-shown' is set to true

### ISSUE THREAD

**Issue by SimmsRyan97** [DavideBlade/HealthBar-Reloaded#23]
I noticed with mobs that the health isn't appearing unless I have 'always-shown' set to true.

I am using style number 3 (the hearts) but just checked style number 1 for example and it still doesn't work.

Here is my config:
```
mob-bars:
  
  # Choose to enable or disable mob health bar.
  enable: true
  
  # Should the bar be shown on renamed mobs? If so, how?
  # You can choose between "override", "append", and "no".
  show-on-named-mobs: override
  
  # The style for the bar. You can choose between 5 style (1,2,3,4,5).
  display-style: 1
  
  # Always show health bars on all the valid mobs.
  always-shown: false
  
  # Use text instead of bar.
  text-mode: false
  
  # Use your custom text, you will need to set 'text-mode: true'
  custom-text-enable: false
  
  # The custom text. You can use these placeholder:
  # {name} = the name of the mob hit.
  # {health} = the current health.
  # {max} = the maximum health.
  # <3 = a hearth symbol (❤)
  # &4 / &n / &k ... = all the formatting codes.
  #
  # For example this will be displayed as 'Creeper - 16/20'
  custom-text: '{name} - &a{health}/{max}'
  
  # The health bar is shown for the specified time when the mob is hit.
  # In other words, after the time specified by the hit has passed, the bar is hidden again.
  # You will need to set 'always-shown: false'.
  hide-delay-seconds: 5
  
  # If enabled, health bars on mobs will be shown only if the player looks directly at him.
  show-only-if-looking: false
  
  # You can choose to use your own made bars, it will override the previous settings.
  use-custom-file: false
  
  # A list of disabled worlds for mob bars.
  # To enable all worlds, use: disabled-worlds: ''
  disabled-worlds: ''
  
  # These mobs won't show the health.
  # The names are the same in locale.yml.
  # To enable all mobs, use: disabled-types: ''
  disabled-types: ''
```
