### ISSUE TITLE
The bars do not disappear

### ISSUE THREAD

**Issue by FePMaK** [DavideBlade/HealthBar-Reloaded#24]
Help me please
Hide-delay-seconds setting: does not work
![Снимок экрана 2024-10-09 212258](https://github.com/user-attachments/assets/250d52ae-9042-45a3-b571-5a07b8f04ec5)
![изображение](https://github.com/user-attachments/assets/47793dd4-1e9c-4a3a-ab21-0af8c09e91eb)

**Comment by DavideBlade** [comment]
Please send me the whole config.yml.
What is the plugin version? Spigot version?

**Comment by FePMaK** [comment]
```
#               ---- + HealthBar by filoghost + ----
#           
#           Please read the instructions before editing:
# http://dev.bukkit.org/bukkit-plugins/health-bar/pages/configuration
#              
#               ---- + ---------------------- + ----
player-bars:
  enable: false
  after-name:
    enable: true
    display-style: 1
    always-shown: true
    text-mode: true
    hide-delay-seconds: 5
    use-custom-file: false
  below-name:
    enable: false
    text: '&c<3'
    use-proportion: true
    proportional-to: 20
    display-raw-hearts: false
  world-disabling: false
  disabled-worlds: world_nether,world_the_end
mob-bars:
  enable: true
  show-on-named-mobs: true
  display-style: 3
  always-shown: false
  text-mode: false
  custom-text-enable: false
  custom-text: ''
  hide-delay-seconds: 3
  show-only-if-looking: false
  use-custom-file: false
  world-disabling: false
  disabled-worlds: world_nether,world_the_end
  type-disabling: false
  disabled-types: creeper,zombie,skeleton,iron_golem
hooks:
  epicboss: false
fix-tab-names: true
fix-death-messages: true
update-notification: true
use-player-bar-permissions: false
override-other-scoreboard: false
```

Plugin version - 1.8.3 | Paper Version - 1.21.1-119
