### ISSUE TITLE
Looking and on hit

### ISSUE THREAD

**Issue by crazyboy13usa** [DavideBlade/HealthBar-Reloaded#26]
This was an issue on the on the old version dont know if it was carried over to the new reloaded version.

When both seeing hearts when attacking and viewing is enabled the harts only display when both conditions are true.  When you hit a cow and it runs off you only see the hearts if you are able to keep your eye on it.  This should not work this way currently its set to only display when both hit and look.  It should be when Hitting OR looking.  This way if you hit a mob and it runs off u can see the hearts as well as if you stare at one.

**Comment by DavideBlade** [comment]
At the moment it works as you say, and this is the expected behavior. Depending on the effect you want to achieve, you might consider showing the bar for a limited time after the hit with the following configuration:
```yaml
mob-bars:
  enable: true
  always-shown: false
  show-only-if-looking: false
  hide-delay-seconds: 5
```
In this way, after you hit a cow, you can see its health for five seconds, regardless of whether you keep staring at it or not.

**Comment by crazyboy13usa** [comment]
I would also like the ability to see it when looking at them without hitting them.  It just adds a weird effect the way it is.  The way i envisioned it to be would be if looking at a cow i would see the hearts.  when hitting them and they run off i would see the hearts even if not directly staring at them when hitting them.  Having both options turned on makes a weird effect where you only see the hearts when both scenarios are true.  Hitting them and keeping your eyes locked on them as they run off.  Like i said it should be the opposite.  You see their hearts when either is true not both.
Maybe make another option (show-also-if-looking) 
anyways thanks for the fast response and for making such a great plugin

**Comment by DavideBlade** [comment]
These are busy weeks. I will see what I can do to add this feature but there will be no updates in the short term (weeks or months).

**Comment by Alyaqdhans** [comment]
if possible also add `hidden-when-full` it will be helpful to see if someone low health and not be annoying and show all times.

Also, is there any way to hide it from chat?

**Comment by DavideBlade** [comment]
> Also, is there any way to hide it from chat?

@Alyaqdhans It should be displayed in chat in Minecraft vanilla. If you use other plugins, then it depends on them and what mechanism they are using. In general, assuming you are referring to the death messages, you can try to configure `bar-in-death-messages: false`. But again, this depends on the other plugins.

**Comment by DavideBlade** [comment]
Hello @crazyboy13usa and @Alyaqdhans. I will try to implement both of your requests in the next version with this `config.yml` change:

```yaml
player-bars:
    # When should the health bar be shown on players?
    # - always    = always visible
    # - on-damage = shown when the player is damaged
    # - below-x%  = shown when player's health drops below the given % (1–99)
    show-condition: on-damage
    
    # How long, in seconds, the health bar after the player's name remains visible once shown.
    # Applies to all time-based 'show-condition': on-damage, below-x%.
    # Use -1 to keep the bar visible indefinitely once triggered.
    hide-delay-seconds: 5

mob-bars:
  # When should the health bar be shown on all the valid mobs?
  # - always             = always visible
  # - always-when-look   = always visible when looking at the mob
  # - on-damage          = shown when the mob is damaged
  # - on-damage-or-look  = shown when the mob is damaged OR when looked at
  # - on-damage-and-look = shown when the mob is damaged when looking at it
  # - below-x%           = shown when mob's health drops below the given % (1–99)
  show-condition: on-damage

  # How long, in seconds, the health bar remains visible once shown.
  # Applies to all time-based 'show-condition': on-damage, on-damage-or-look, on-damage-and-look, below-x%.
  # Use -1 to keep the bar visible indefinitely once triggered.
  hide-delay-seconds: 5
```

`always-shown` and `show-only-if-looking` will be removed.
